export default {
    version: '0.1.31',
    technologies: [
        "angularjs",
        "apache thrift",
        "asp.net core",
        "c++",
        "codeigniter",
        "dart",
        "django",
        "express.js",
        "fastapi",
        "flask",
        "go",
        "grails",
        "hapi.js",
        "hibernate",
        "java",
        "julia",
        "kotlin",
        "laravel",
        "loopback",
        "micronaut",
        "nestjs",
        "next.js",
        "phoenix",
        "php",
        "play",
        "python",
        "rails",
        "react",
        "ruby",
        "ruby on rails",
        "scala",
        "spark",
        "spring",
        "strapi",
        "symfony",
        "swift",
        "typescript",
        "vaadin",
        "vue.js"
      ],
    prompts: [

    ],
};